name: XeonSuiteChat
version: ${project.version}
description: Chatplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.chat.Chatplugin
softdepend: [Vault]
load: POSTWORLD
depend: [XeonSuiteBukkit]

commands:
  gc:
    aliases: [guildchat, guildc]
    description: GuildChat
  msg:
    aliases: [pm, tell]
    description: MSG
  r:
    aliases: [reply]
    description: MSG
  tc:
    aliases: [ac, a]
    description: TeamChat
  g:
    aliases: [global, gc, me]
    description: GlobalChat
  afk:
    description: AFK
  spy:
    aliases: [socialspy]
    description: SocialSpy

permissions:
    xeonSuite.chat.team:
        description: Alle User Permissions
        children:
            xeonSuite.chat.user: true
            xeonSuite.chat.socialspy: true
            xeonSuite.chat.bypass: true
            xeonSuite.chat.staff: true
    xeonSuite.chat.user:
        description: Alle User Permissions
        children:
            xeonSuite.chat.gchat: true
            xeonSuite.chat.pm: true
            xeonSuite.chat.reply: true
            xeonSuite.chat.afk: true
            xeonSuite.chat.global: true
            xeonSuite.chat.use: true
    xeonSuite.chat.gchat:
        description: GuildChat
        default: op
    xeonSuite.chat.afk:
        description: GuildChat
        default: op
    xeonSuite.chat.pm:
        description: GuildChat
        default: op
    xeonSuite.chat.reply:
        description: GuildChat
        default: op
    xeonSuite.chat.staff:
        description: GuildChat
        default: op
    xeonSuite.chat.global:
        description: GuildChat
        default: op
    xeonSuite.chat.use:
        description: GuildChat
        default: op
    xeonSuite.chat.socialspy:
        description: Socialspy
        default: op
    xeonSuite.chat.bypass:
        description: Bypass
        default: op