name: MineSuiteChat
version: ${project.version}
description: ChatPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.chat.ChatPlugin
load: POSTWORLD
depend: [MineSuiteCore, Vault, Votifier]
api-version: 1.13
commands:
  testvote:
    description: TeamChat
  msg:
    aliases: [pm, tell]
    description: MSG
  r:
    aliases: [reply]
    description: MSG
  tc:
    aliases: [ac, a]
    description: TeamChat
  g:
    aliases: [global, me]
    description: GlobalChat
  h:
    aliases: [trade, handel]
    description: TradeChat
  bc:
    aliases: [broadcast]
    description: BroadCast
  afk:
    description: AFK
  spy:
    aliases: [socialspy]
    description: SocialSpy

permissions:
    mineSuite.chat.team:
        description: Alle User Permissions
        children:
            mineSuite.chat.user: true
            mineSuite.chat.socialspy: true
            mineSuite.chat.bypass: true
            mineSuite.chat.staff: true
            mineSuite.chat.broadcast: true
            mineSuite.chat.testvote: true
    mineSuite.chat.user:
        description: Alle User Permissions
        children:
            mineSuite.chat.pm: true
            mineSuite.chat.reply: true
            mineSuite.chat.afk: true
            mineSuite.chat.global: true
            mineSuite.chat.use: true
            mineSuite.chat.trade: true
    mineSuite.chat.afk:
        description: GuildChat
        default: op
    mineSuite.chat.pm:
        description: GuildChat
        default: op
    mineSuite.chat.reply:
        description: GuildChat
        default: op
    mineSuite.chat.staff:
        description: GuildChat
        default: op
    mineSuite.chat.global:
        description: GuildChat
        default: op
    mineSuite.chat.trade:
        description: TradeChat
        default: op
    mineSuite.chat.broadcast:
        description: BroadcastChat
        default: op
    mineSuite.chat.use:
        description: GuildChat
        default: op
    mineSuite.chat.socialspy:
        description: Socialspy
        default: op
    mineSuite.chat.bypass:
        description: Bypass
        default: op
    mineSuite.chat.testvote:
        description: Bypass
        default: op